config:
  lokiAddress: http://loki:3100/loki/api/v1/push

initContainer:
  enabled: true
  fsInotifyMaxUserInstances: 1024

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 100%

resources:
  requests:
    memory: 256Mi
  limits:
    memory: 256Mi

serviceMonitor:
  enabled: true

tolerations:
  - effect: NoSchedule
    operator: Exists
